[versions]
agp = "8.8.2"
circleimageview = "3.1.0"
fragmentKtx = "1.8.8"
# logical parts
fragmentKtxVersion = "1.8.8"
glide = "4.16.0" # image loader
javafaker = "1.0.2" # test data
# DI
hilt = "2.56.2"
ksp = "2.1.20-1.0.31"
# ________________
kotlin = "2.1.20"
coreKtx = "1.16.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.7.1"
material = "1.12.0"
activity = "1.10.1"
constraintlayout = "2.2.1"
navigationUiKtx = "2.9.0"
picasso = "2.8"
picassoTransformations = "2.4.0"
roomCompilerProcessingTesting = "2.7.2"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "fragmentKtx" }
androidx-fragment-ktx-v188 = { module = "androidx.fragment:fragment-ktx", version.ref = "fragmentKtxVersion" }
androidx-navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigationUiKtx" }
androidx-navigation-safe-args-gradle-plugin = { module = "androidx.navigation:navigation-safe-args-gradle-plugin", version.ref = "navigationUiKtx" }
androidx-navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigationUiKtx" }
circleimageview = { module = "de.hdodenhof:circleimageview", version.ref = "circleimageview" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
javafaker = { module = "com.github.javafaker:javafaker", version.ref = "javafaker" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
picasso = { module = "com.squareup.picasso:picasso", version.ref = "picasso" }
androidx-room-compiler-processing-testing = { group = "androidx.room", name = "room-compiler-processing-testing", version.ref = "roomCompilerProcessingTesting" }
picasso-transformations = { module = "jp.wasabeef:picasso-transformations", version.ref = "picassoTransformations" }
hilt-android = {module = "com.google.dagger:hilt-android", version.ref="hilt"}
hilt-android-compiler = {module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt"}


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
android-navigation-safeargs = {id = "androidx.navigation.safeargs.kotlin", version.ref = "navigationUiKtx"}
kotlin-parcelize = {id = "kotlin-parcelize"}
hilt = {id = "com.google.dagger.hilt.android", version.ref="hilt"}
ksp = {id = "com.google.devtools.ksp", version.ref="ksp"}


